### ISSUE TITLE
Bug: Cannot open sound config when assigned file that isn't a sound file for the sound

### ISSUE THREAD

**Issue by ValuedEmployee** [Aedif/token-sounds#4]
I messed up when I made some sounds, and copy pasted an image path into the sound path by accident. Now I can't open the sound again by right clicking, and I get some errors on startup of the scene or when attempting to play the sound. I'm unable to remove the sounds through the menu.

![Screenshot 2024-04-17 at 2 34 19 PM](https://github.com/Aedif/token-sounds/assets/105574010/7c12a522-6e69-426d-b399-d76c766ea77a)
![Screenshot 2024-04-17 at 2 32 10 PM](https://github.com/Aedif/token-sounds/assets/105574010/0d3cbfe0-007d-429d-8407-28bcc29b33bc)

Disabled all other modules besides lib wrapper and I'm still getting this bug.
Foundry version: v11, build 315
D&D Version: 3.1.2

In the meantime, is there a way to remove the sounds through a file somewhere instead?

**Comment by Aedif** [comment]
Should be fixed in 1.2.1

Updating sounds with non-audio links should also now be impossible.

**Comment by ValuedEmployee** [comment]
![Screenshot 2024-04-17 184121](https://github.com/Aedif/token-sounds/assets/105574010/98418a17-e3aa-4ad6-a5f2-aa06296159c9)

Can confirm, I was able to remove the problem sounds! Thanks for the save!!
